### ISSUE TITLE
希望支持表格的固定列能力

### ISSUE THREAD

**Issue by Too-Tao** [JDFED/drip-table#100]
**Describe alternatives you've considered**
需要开放表格列的fixed能力

**Additional context**
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/40811570/158340518-0cf1d95e-8338-400a-8909-f5afcaa70cd4.png">

**Comment by tinymins** [comment]
已完成，更新到最新版本即可。
https://drip-table.jd.com/drip-table/schema/columns/fixed
