### ISSUE TITLE
表头Header部分下载整个表格按钮及富文本信息内容的能力

### ISSUE THREAD

**Issue by Too-Tao** [JDFED/drip-table#101]
**Is your feature request related to a problem? Please describe.**
需要表头Header中自定义组件示例，如下载按钮配置、自定义富文本内容等

**Additional context**
富文本
<img width="470" alt="image" src="https://user-images.githubusercontent.com/40811570/158341860-af35aec4-4a93-46d6-bd52-4de64fc90741.png">
下载按钮
<img width="280" alt="image" src="https://user-images.githubusercontent.com/40811570/158341788-c67a614d-59e6-4832-94d8-ac36218c04bb.png">

**Comment by tinymins** [comment]
http://drip-table.jd.com/drip-table/props/slots 最新版已可用。
