### ISSUE TITLE
【drip-table】未知组件被渲染为整个record

### ISSUE THREAD

**Issue by CrazyWood007** [JDFED/drip-table#107]
**Describe the bug**
如果schema中有一个column的类型对应组件没有导入，则该列将渲染为整行数据

**Expected behavior**
希望能展示空白或者接受自定义的处理方式

**Screenshots**
![image](https://user-images.githubusercontent.com/44600593/160582843-395f4cad-0ece-41a1-8023-c09bde257b38.png)

**Additional context**
{
    "$schema": "http://json-schema.org/draft/2019-09/schema#",
    "pagination": false,
    "columns": [
        {
            "key": "custom::xxxxx_17fd4f5d116-11cf",
            "dataIndex": "",
            "title": "",
            "group": "",
            "description": "",
            "ui:type": "custom::xxxxx",
            "ui:props": {
                "render": "return ''"
            },
            "type": "string",
            "render": "return ''",
            "align": "center"
        }
    ]
}

**Comment by tinymins** [comment]
fixed, drip-table@1.3.4
