### ISSUE TITLE
希望有介绍和安装视频

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#11]
**Is your feature request related to a problem? Please describe.**
直接看视频方便新手快速了解项目。希望在首页可以有一个介绍和安装视频，方便用户学习

**Comment by XPF-821** [comment]
Please understand that the video is in preparation
视频准备中，敬请谅解

**Comment by raoenhui** [comment]
官网文档已经补全，http://drip-table.jd.com
