### ISSUE TITLE
【drip-table-generator】feat：表格增加展示模式，要求组件开发时配置默认展示值，一键切换到展示模式

### ISSUE THREAD

**Issue by Too-Tao** [JDFED/drip-table#113]
目前generator中初始化的mock数据不能自定义，需要支持初始化配置默认展示值

**Comment by helloqian12138** [comment]
mock 数据是可以自定义的，具体可以参考：
https://drip-table.jd.com/drip-table-generator/functions/api

下面三个字段可以满足该需求：
<img width="824" alt="图片" src="https://user-images.githubusercontent.com/13211910/162942490-3191cb21-8487-445e-a352-e236f2110487.png">
