### ISSUE TITLE
【drip-table-generator】删除初始化无数据情况下展示的三角感叹号图标

### ISSUE THREAD

**Issue by Too-Tao** [JDFED/drip-table#119]
当generator里面给定schema，但未给组件传初始Data值信息，会出现感叹号图标，建议将感叹号图标删除
<img width="528" alt="image" src="https://user-images.githubusercontent.com/40811570/166890613-ebc085af-5a80-440e-8bd5-77516d6bcf60.png">

**Comment by helloqian12138** [comment]
这块是我做的兜底提示，不是bug

**Comment by helloqian12138** [comment]
最新效果
![image](https://user-images.githubusercontent.com/13211910/173319879-c022e312-5f95-4cf7-860b-00764b9dcd23.png)
