### ISSUE TITLE
【Bug】旧版本generator生成的schema和新版的table schema校验冲突

### ISSUE THREAD

**Issue by Too-Tao** [JDFED/drip-table#126]
[old_schema.txt](https://github.com/JDFED/drip-table/files/8844460/old_schema.txt)
报错内容：
![image](https://user-images.githubusercontent.com/40811570/172161106-ecfbeed7-f923-4c40-a897-8140689e23a9.png)
需要升级table和generator，如何解决旧版schema不兼容新包问题

**Comment by raoenhui** [comment]
升级generator，配置下pageSize即可
