### ISSUE TITLE
【drip-table】需要兼容旧版Schema中参数pageSize、size:default

### ISSUE THREAD

**Issue by Too-Tao** [JDFED/drip-table#131]
pageSize兼容问题：table需要兼容schema中没有pageSize问题
![image](https://user-images.githubusercontent.com/40811570/173320417-e12478b1-7457-4d47-a272-338c9106a578.png)
报错：
![image](https://user-images.githubusercontent.com/40811570/173320464-8755c4f1-3a0b-410f-b45c-ff4ff44630e5.png)

size兼容问题：table校验size属性值为defalut时不通过
![image](https://user-images.githubusercontent.com/40811570/173319990-41919c6c-9472-43d5-a368-35c903f4a53b.png)
报错：
![image](https://user-images.githubusercontent.com/40811570/173320049-5da6ca1b-0557-4324-b4e7-81ba01c65d1c.png)

**Comment by tinymins** [comment]
更新到 1.3.15 即可

https://drip-table.jd.com/drip-table/changelog#20220615-v1315
