### ISSUE TITLE
官网文档API目录希望可以新增中文解释

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#134]
**Is your feature request related to a problem? Please describe.**
目前文档很难找到想要的功能

**Describe the solution you'd like**
官网文档API目录希望可以新增中文解释

**Describe alternatives you've considered**
目录上既有英文又有中文，方便查看搜索

**Additional context**
类似https://ant.design/components/steps-cn/
![image](https://user-images.githubusercontent.com/14011130/173529496-e444711f-821a-488d-be53-c2ada7410720.png)

而目前table是
![image](https://user-images.githubusercontent.com/14011130/173529701-0f5ac8bc-91b6-46cc-8642-a35ec90a3ab1.png)

**Comment by raoenhui** [comment]
1、顺序，组件->schema(解释)-〉props 属性
2、三层结构，头部合并
3、组件总览图文

**Comment by helloqian12138** [comment]
1、目录结构添加中英文说明：https://drip-table.jd.com/drip-table
2、组件总览添加图文说明：https://drip-table.jd.com/drip-table/components
