### ISSUE TITLE
自定义组件名字长，样式错乱

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#141]
**Describe the bug**
自定义组件名字长，样式错乱

**To Reproduce**
open  http://betah5.m.jd.com/dripworks/index.html#/pageGenerator?appId=206&appName=3D407FC0&appZhName=%E6%81%A9%E6%85%A7%E7%9A%84CMS&moduleType=tableV1_2_0&pageId=845&pageName=%E6%81%A9%E6%85%A7%E7%9A%84%E6%B5%8B%E8%AF%95%E9%A1%B5%E9%9D%A2&pageType=normal&moduleOrder=2&paginationIn=front

**Expected behavior**

**Screenshots**
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/14011130/174786158-f4afdd77-e4db-4ec8-8fe4-ea3062152fc5.png">

**Desktop (please complete the following information):**
 - Drip-table version:latest
 - Drip-table-generator version (optional): latest

**Comment by helloqian12138** [comment]
![image](https://user-images.githubusercontent.com/13211910/175274168-40461fff-4af6-4f3c-b8c7-bba9ad5cf390.png)
