### ISSUE TITLE
表头宽度根据内容自适应

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#150]
**Is your feature request related to a problem? Please describe.**
希望表头和内容宽度过长自动省略号。每列可设置宽度，没有设置的实现自适应省略号。
详情如下：
 列可设置宽度，没有设置的是否可以平均分配 实现自适应，设置 column.ellipsis 可以让单元格内容根据宽度自动省略。https://ant.design/components/table-cn/#components-table-demo-ellipsis-custom-tooltip
![image](https://user-images.githubusercontent.com/14011130/178463264-b0881e3d-609f-41b9-a0bb-53fb436af3df.png)

**Comment by helloqian12138** [comment]
https://drip-table.jd.com/drip-table/schema/table-layout

**Comment by helloqian12138** [comment]
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/13211910/201293914-85612a7b-026f-4d6f-8d5e-13e25da4843c.png">
