### ISSUE TITLE
禁用某行选中功能

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#151]
**Is your feature request related to a problem? Please describe.**
希望新增禁用某行选中功能

**Additional context**
 Example1：https://www.surely.cool/doc/selection#row-selection-and-operation 
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/14011130/178462880-20fa171b-7160-4522-b560-550448a501ea.png">

Example2：https://n3-components.github.io/N3-components/component.html#n3DataTableDocs
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/14011130/178462963-0c7faa7e-32a8-4220-b0a0-def0324efa3d.png">

**Comment by Estherjing** [comment]
[https://drip-table.jd.com/drip-table/props/get-checkbox-props](https://drip-table.jd.com/drip-table/props/get-checkbox-props)
![image](https://user-images.githubusercontent.com/88180229/188415927-1cb21095-a1cc-4651-9e39-0cc01bc5e2d6.png)
