### ISSUE TITLE
条纹配置

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#154]
**Describe the solution you'd like**
实现表格行条纹配置。使表格会间隔显示不同颜色，用于区分不同行数据。

**Additional context**
  Example：https://iview.github.io/components/table
![image](https://user-images.githubusercontent.com/14011130/178466914-9dc8d86f-9e15-48bf-8336-bf5cdb911980.png)

**Comment by helloqian12138** [comment]
需要同时支持自定义hover样式

**Comment by Estherjing** [comment]
[https://drip-table.jd.com/drip-table/schema/stripe](https://drip-table.jd.com/drip-table/schema/stripe)
![image](https://user-images.githubusercontent.com/88180229/188415183-96ddb06f-a93a-443f-83c2-18b920847ed6.png)
