### ISSUE TITLE
表格生成器实现左中右布局

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#157]
**Describe the solution you'd like**
支持左中右布局，https://joyspace.jd.com/page/UT9U4NisPpINScQqCqaa，https://airtable.com/app4UEoTvRivhCqSz/tbl0Ow5PFHudKw3QG/viwJcImaCJbUeHajj?blocks=hide

**Comment by Estherjing** [comment]
![image](https://user-images.githubusercontent.com/88180229/181733703-6f9c6076-4ed0-4757-a589-91539992fb88.png)

**Comment by helloqian12138** [comment]
<img width="1775" alt="image" src="https://user-images.githubusercontent.com/13211910/204798180-1476bcf3-718f-4420-a03a-4a55fdb0bfbb.png">
