### ISSUE TITLE
changelog缺失

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#158]
**Is your feature request related to a problem? Please describe.**
changelog缺失，不方便查看新增功能

**Describe the solution you'd like**
官网文档优化。Api菜单增加中文，新增changelog，方便用户查看不同版本新增功能。2、表格生成器左中右布局详细方案 3、筛选器详细方案调研编写。

**Comment by raoenhui** [comment]
https://github.com/JDFED/drip-table/releases
参照
https://github.com/ant-design/ant-design/releases
https://github.com/facebook/react/releases

**Comment by Estherjing** [comment]
![image](https://user-images.githubusercontent.com/88180229/186119918-3039061c-c093-428b-8c4e-a8d51ea093ee.png)
https://github.com/JDFED/drip-table/releases
