### ISSUE TITLE
省略号缺失

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#168]
**Expected behavior**
没有省略号
[A clear and concise description of what you expected to happen.](https://drip-table.jd.com/drip-table/schema/ellipsis)

**Screenshots**
![image](https://user-images.githubusercontent.com/14011130/178726239-ecff224b-9537-48b7-80aa-1fcf4835381d.png)

**Comment by tinymins** [comment]
没问题吧？Schema 没有开启省略号，开启了就有了。

**Comment by helloqian12138** [comment]
文档和 ellipsis 属性已经更改成 tableLayout, 但是由于 css 的  -webkit-box 不是标准写法，仍需修复

**Comment by helloqian12138** [comment]
![image](https://user-images.githubusercontent.com/13211910/186415159-12542571-a1ba-4476-8064-ced2e72653ff.png)
