### ISSUE TITLE
打开demo链接，点击子列表报错

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#169]
**To Reproduce**
打开demo链接，点击子列表报错，[https://drip-table.jd.com/drip-table/sample](https://drip-table.jd.com/drip-table/sample)

**Screenshots**
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/14011130/178913932-a560ac40-b94e-4d43-ba92-0992e0ea31f4.png">

**Comment by helloqian12138** [comment]
由于demo写法有误，无法编译导致，已修复
https://drip-table.jd.com/drip-table/sample
