### ISSUE TITLE
粘性头部希望换个名字

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#171]
**To Reproduce**
1. Go to [https://drip-table.jd.com/demo](https://drip-table.jd.com/demo)
**Screenshots**
粘性头部不理解
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/14011130/178965069-57a79b2a-3cc8-46c2-a81e-ad1a4a683718.png">

**Comment by Estherjing** [comment]
已替换为冻结表头
