### ISSUE TITLE
希望列表生成器组件有默认数据，方便操作

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#172]
**Is your feature request related to a problem? Please describe.**
使用表格生成器新增组件时，无法看到效果
**Describe the solution you'd like**
希望表头名称有默认值，另外有开放api开放兜底数据
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/14011130/179479467-ab07d2fa-c93b-4521-b4a8-0f0e871ba5f0.png">

**Comment by helloqian12138** [comment]
可以通过 Generator 的自定义属性面板功能来实现
{
      'ui:type': 'text',
      type: 'string',
      group: '基础组件库',
      fieldKey: 'mock_builtin_text',
      title: '内置文本',
      attrSchema: [
        {
           name: 'title',
           group: '组件属性',
           'ui:title': '表头名称',
           'ui:type': 'text',
           type: 'string',
           default: '文本',
        },
        {
           name: 'options.defaultValue',
          group: '组件属性',
          'ui:title': '兜底文案',
          'ui:type': 'input',
          'ui:description': {
              trigger: 'hover',
              type: 'icon',
              title: '当数据不下发时展示的兜底文案',
          },
          default: '',
        },
   ]
}
具体参考文档链接：https://drip-table.jd.com/drip-table-generator/props/custom-component-panel

**Comment by raoenhui** [comment]
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/14011130/181409563-ff56131a-7a1d-4b50-ab55-928496f20e2c.png">
