### ISSUE TITLE
table的容器固定高度，内容滚动，分页器被隐藏，希望可以header中展示分页

### ISSUE THREAD

**Issue by Henry129999** [JDFED/drip-table#180]
**Is your feature request related to a problem? Please describe.**
在水滴工作台新的布局中，展示table的容器可能会存在固定高度，内容支持滚动的情况下，导致底部的分页被隐藏了，希望支持在header中展示分页的能力。

**Describe the solution you'd like**
希望支持在header中展示分页的能力。

**Describe alternatives you've considered**
/

**Additional context**
![image](https://user-images.githubusercontent.com/36527485/181409943-6619d7bd-5c61-4e81-ba80-f7370f61732d.png)

**Comment by helloqian12138** [comment]
已支持
链接：https://drip-table.jd.com/demo
预览：
![image](https://user-images.githubusercontent.com/13211910/182310519-372dee20-acbc-4e1b-bd50-9524f850de74.png)
