### ISSUE TITLE
文本组件希望支持一键复制

### ISSUE THREAD

**Issue by CrazyWood007** [JDFED/drip-table#182]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
文本组件可设置一键复制，设置后，在文本前或文本后，展示复制图标，点击复制内容到剪切板

**Describe alternatives you've considered**

**Additional context**

**Comment by renwenci** [comment]
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/25983242/188420468-131a9986-8667-447d-b443-3785a97e4ef0.png">
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/25983242/188420546-5b9b42a5-54b4-413a-b654-c9b376db402b.png">
已添加该功能
