### ISSUE TITLE
希望生成器支持左中右布局

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#199]
**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]](https://joyspace.jd.com/page/sXyjQrd3F5qW0R8qeojb)

**Comment by helloqian12138** [comment]
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/13211910/199661151-7d13ab70-4a94-40e6-a490-3bcba9e4062b.png">
