### ISSUE TITLE
官网内容丰富

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#2]
**Is your feature request related to a problem? Please describe.**
官网需要添加github地址

**Describe the solution you'd like**
建议在左上角添加一个github的图标

**Additional context**

![image](https://user-images.githubusercontent.com/14011130/145944076-5543f45d-0088-47a3-8ace-3c52552dda9c.png)

**Comment by XPF-821** [comment]
The suggestion has been received and will be completed immediately

**Comment by XPF-821** [comment]
We have received the suggestion and will finish it right away
我们已经收到您的建议，马上完成

**Comment by XPF-821** [comment]
The proposal has been completed. Thank you for your participation.![image](https://user-images.githubusercontent.com/75602122/147313155-f8e2fc27-8e30-4376-b52d-747710705ca8.png)该建议已完成，感谢提醒。
