### ISSUE TITLE
生成器行高json错误

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#201]
**Describe the bug**

生成器行高json错误

**Screenshots**
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/14011130/183838134-74d93ccd-be96-423c-a8ca-4fb0a58bbbe6.png">

**Comment by helloqian12138** [comment]
![image](https://user-images.githubusercontent.com/13211910/186415377-c1aee7fd-ea80-4462-8627-d461513d4728.png)
