### ISSUE TITLE
文本组件加固定高度输入框

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#202]
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/14011130/183839622-e751c26c-f578-40fd-8d2a-cdb4c52776b9.png">

**Comment by renwenci** [comment]
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/25983242/188419201-491065e6-ee7e-468c-9144-ec0308d47536.png">
已添加功能

**Comment by renwenci** [comment]
`
