### ISSUE TITLE
表格行选择功能希望支持禁用

### ISSUE THREAD

**Issue by CrazyWood007** [JDFED/drip-table#203]
**Is your feature request related to a problem? Please describe.**
希望能根据某些条件设置某行数据是否被禁用（不可选择/取消选择）
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/44600593/183848608-32ff4bec-736f-4a8e-84e3-8fa3e118f4e9.png)

**Describe alternatives you've considered**
希望通过某种方式设置该行是否禁用，比如schema中设置`rowSelectionDisabledKey`为`rowSelectionDisabled`，则`rec.rowSelectionDisabled`为`true`的行，checkbox处于禁用状态

**Additional context**
没有实现方式的要求，但是需要这个功能，希望综合考虑下，给出一种合适的方案。

**Comment by tinymins** [comment]
drip-table 最新已支持 https://drip-table.jd.com/drip-table/props/row-selectable
