### ISSUE TITLE
columns中过滤器默认值demo没有看到过滤器

### ISSUE THREAD

**Issue by Estherjing** [JDFED/drip-table#207]
**Describe the bug**
columns中过滤器默认值demo没有看到过滤器
[ https://drip-table.jd.com/drip-table/schema/columns/default-filtered-value]( https://drip-table.jd.com/drip-table/schema/columns/default-filtered-value)

**Screenshots**
![image](https://user-images.githubusercontent.com/88180229/185586195-f9fa139a-67a2-4c0f-8244-269cbb9b3b6d.png)

**Comment by tinymins** [comment]
您可能使用了 alpha 版本，正式版均正常。
