### ISSUE TITLE
渲染器的columns中的fixed属性没有直观的显示效果

### ISSUE THREAD

**Issue by Estherjing** [JDFED/drip-table#208]
**Describe the bug**
渲染器的columns中的fixed属性没有直观的显示效果
[https://drip-table.jd.com/drip-table/schema/columns/fixed](https://drip-table.jd.com/drip-table/schema/columns/fixed)

**Screenshots**
![截屏2022-08-19 下午5 26 36](https://user-images.githubusercontent.com/88180229/185589025-362c766b-bba2-4ca9-bfa7-6d489f73dd35.png)

**Comment by raoenhui** [comment]
已修复，https://drip-table.jd.com/drip-table/schema/columns/fixed/
