### ISSUE TITLE
连接组件的链接可以带参数吗？

### ISSUE THREAD

**Issue by jin1031960096** [JDFED/drip-table#22]
连接组件的链接可以带参数吗？
![0E486616-E1EA-47DB-990F-3F0B06EEC10E](https://user-images.githubusercontent.com/61078465/146751082-029e556f-0881-444b-9955-72cc92c7b2fa.jpeg)

**Comment by tinymins** [comment]
#23，已支持，通过 `${rec.name}` 方式引用参数，感谢反馈。
