### ISSUE TITLE
希望图片组件可以支持设置兜底图

### ISSUE THREAD

**Issue by CrazyWood007** [JDFED/drip-table#223]
**Is your feature request related to a problem? Please describe.**
在2.0版本中，图片组件，值为null时，图裂开而不是展示兜底图

**Describe the solution you'd like**
在图片组件无值（''/null等等）时或图片加载异常时，希望都可以展示兜底图，且希望能支持配置兜底图

**Describe alternatives you've considered**
对值进行默认兜底图链接兜底，onError改写src为兜底图
另外要防止兜底图设置异常，可能引发死循环
**Additional context**
![image](https://user-images.githubusercontent.com/44600593/188419616-c85633ca-1a7f-4596-8f6c-70bc807f03a5.png)

**Comment by renwenci** [comment]
已发布该功能 可参考数据处理的文档 https://drip-table.jd.com/drip-table/schema/data-process
