### ISSUE TITLE
[BUG]selectedRowKeys不受控

### ISSUE THREAD

**Issue by CrazyWood007** [JDFED/drip-table#232]
**Describe the bug**
开启行可选择后，表格对selectedRowKeys没有反应，选中态不受控制

**To Reproduce**
https://codesandbox.io/s/driptable-2-0-1-selectedrowkeys-k6nn0b

**Expected behavior**
selectedRowKeys受控

**Desktop (please complete the following information):**
 - Drip-table version:2.0.1
 - Drip-table-generator version (optional):
 - React version:

**Comment by tinymins** [comment]
fixed in `drip-table@2.0.2`
