### ISSUE TITLE
th支持设置提示信息

### ISSUE THREAD

**Issue by CrazyWood007** [JDFED/drip-table#245]
**Is your feature request related to a problem? Please describe.**
表头th希望能设置提示信息

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![974d9737-ab98-4bc0-94e1-384008ab70c6](https://user-images.githubusercontent.com/44600593/194824074-ecb12df7-25fd-4034-bc16-145f1179629e.png)

**Comment by raoenhui** [comment]
<img width="723" alt="image" src="https://user-images.githubusercontent.com/14011130/195023866-bd1e1729-a6d8-44b6-8c19-336365bd6f6f.png">

**Comment by raoenhui** [comment]
https://ace.jd.com/interaction/#/manage

**Comment by helloqian12138** [comment]
<img width="339" alt="image" src="https://user-images.githubusercontent.com/13211910/199662438-7723ea0d-fe5c-42fc-b22a-f167628dd784.png">
