### ISSUE TITLE
表格数据 demo支持格式化

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#248]
[demo链接](https://drip-table.jd.com/demo/)
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/14011130/196113056-dd7de742-7f00-484c-8831-7845adef92c0.png">

**Comment by helloqian12138** [comment]
![屏幕录制2022-11-03-下午2 18 40](https://user-images.githubusercontent.com/13211910/199658703-ec329897-fccf-40e3-aae9-b7f36b14e263.gif)

**Comment by raoenhui** [comment]
添加按钮，让用户自己格式化
