### ISSUE TITLE
表格渲染器demo，json按钮右移

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#258]
**Is your feature request related to a problem? Please describe.**
无法找到修改json的地方
**Describe the solution you'd like**
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/14011130/199434098-23a4b279-74fb-4648-b0fe-9860fca7d5da.png">

**Comment by Estherjing** [comment]
https://drip-table.jd.com/drip-table/sample
![image](https://user-images.githubusercontent.com/88180229/201294169-4c4d9e54-a861-4aff-b4b8-55d85f136bc9.png)
