### ISSUE TITLE
搭建场景，左侧边栏通过图标查找组件比较困难

### ISSUE THREAD

**Issue by Henry129999** [JDFED/drip-table#266]
**Is your feature request related to a problem? Please describe.**
搭建场景，左侧边栏通过图标查找组件比较困难

**Describe the solution you'd like**
期望直接展示组件名，而不是hover展示

**Describe alternatives you've considered**
/

**Additional context**
![image](https://user-images.githubusercontent.com/36527485/201818393-eadaf2eb-5cc6-4fbc-ad25-6df79d3a4352.png)

**Comment by Estherjing** [comment]
已更新  https://drip-table.jd.com/demo/

![image](https://user-images.githubusercontent.com/88180229/205542060-2634ff33-ff19-468a-8e41-0357f8ddd7a5.png)
