### ISSUE TITLE
新增数字框组件并支持编辑

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#267]
具体方案为：https://joyspace.jd.com/page/ASPubuIhVqw2Tvp7Nn6V
数字组件
格式：decimal小数  integer 整数
precision精度（小数情况下）: 1.0 1.00 1.000 1.0000 1.00000
是否允许负数
是否千分位分割
单元格里可以设置数值范围，加加减减

**Comment by Estherjing** [comment]
目前千分位分割不支持，后续支持

![image](https://user-images.githubusercontent.com/88180229/205541673-6a4515b5-bd5e-4da1-ba9d-8b70f0e24064.png)
