### ISSUE TITLE
下拉组合组件太窄

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#271]
**Is your feature request related to a problem? Please describe.**
下拉组合组件太窄，操作不方便

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/14011130/203055933-3cb120c2-08b4-4bfe-80ac-bd1dcca06a4c.png)
下拉框宽度加宽，展示至少4个字

**Comment by Estherjing** [comment]
![image](https://user-images.githubusercontent.com/88180229/205541514-2e7bfd8f-e7e1-4a80-b924-ce58c7abba82.png)
