### ISSUE TITLE
表格生成器需要暴露渲染器对应的属性

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#275]
**Is your feature request related to a problem? Please describe.**
表格生成器需要暴露渲染器对应的方法，方便直接在表格生成器中配置，如果满足批量选择方法调用

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by helloqian12138** [comment]
https://drip-table.jd.com/drip-table-generator/functions/table-props
