### ISSUE TITLE
每行头部圆角、每行间距

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#289]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/14011130/205473378-a0a11941-b67e-4e0d-bd4c-4601f81aafff.png)

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.](https://relay.jd.com/web/project/page/a200ce85-8ded-42a7-b980-08da308d7f01/0/)

**Describe alternatives you've considered**

**Additional context**

**Comment by helloqian12138** [comment]
https://drip-table.jd.com/drip-table-generator/functions/custom-theme
