### ISSUE TITLE
支持垂直布局配置

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#290]
有诉求要垂直向上对齐
![image](https://user-images.githubusercontent.com/14011130/205473764-4d1b974a-5440-4e8d-ab93-b93557fe4a19.png)

<img width="1702" alt="image" src="https://user-images.githubusercontent.com/14011130/205473702-9b7863a4-450f-4e15-aec6-87dd1513c939.png">

组件需要有水平居中、左对齐、右对齐、垂直居中、上对齐、下对齐

**Comment by raoenhui** [comment]
drip-table core支持https://drip-table.jd.com/drip-table/schema/columns/vertical-align

**Comment by helloqian12138** [comment]
<img width="1744" alt="image" src="https://user-images.githubusercontent.com/13211910/209520322-a1383b47-1b98-41fb-b1f4-4aa68ca1aef4.png">
