### ISSUE TITLE
交互升级后，官网样式没有更新

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#304]
**Describe the bug**

**To Reproduce**
1. Go to ['官网](https://drip-table.jd.com/)

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/14011130/206074049-99882dfa-fd90-4a5a-8380-802e3e373ec0.png">
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/14011130/206074196-86f9a7fe-936e-4067-8c9a-d1f465340840.png">

**Comment by raoenhui** [comment]
https://juejin.cn/post/7173583038452858911

**Comment by tinymins** [comment]
已更新
