### ISSUE TITLE
用户反馈，容器里面的组件，如果被隐藏了，就剩下一个删除的x，很容易误触删除

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#309]
**Describe the bug**
![image](https://user-images.githubusercontent.com/14011130/206678671-da873255-93d5-4a5d-b1b2-d1da72cc07c1.png)

**Additional context**
建议搭建界面可以给一个最小宽高，预览界面的可以隐藏掉

**Comment by helloqian12138** [comment]
已解决
<img width="754" alt="image" src="https://user-images.githubusercontent.com/13211910/209521144-be06bb48-a8f7-40da-9824-16776aa0e427.png">
