### ISSUE TITLE
业务组件搭建模式展示，但是预览模式不展示

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#313]
**Describe the bug**
业务组件搭建模式展示，但是预览模式不展示
![image](https://user-images.githubusercontent.com/14011130/206894021-8c032ff1-7829-45f7-bf31-8bf4bddac97c.png)

**Comment by helloqian12138** [comment]
已解决
<img width="1750" alt="image" src="https://user-images.githubusercontent.com/13211910/209520491-e8433c7a-9948-4345-8bbc-25c16dee489a.png">
