### ISSUE TITLE
组件属性面板优化

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#314]
**Is your feature request related to a problem? Please describe.**
组件属性面板优化，方便用户快速查看常用属性

**Describe the solution you'd like**
http://dripworks-fx4dkcsd-pro.local-pf.jd.com/#/2617

![image](https://user-images.githubusercontent.com/14011130/206984575-82788a94-5c66-482a-bada-b3c38ac11794.png)

**Comment by raoenhui** [comment]
https://joyspace.jd.com/pages/T2aMtvyccfpDmOFk8K8k

**Comment by helloqian12138** [comment]
![image](https://user-images.githubusercontent.com/13211910/212861677-8287b230-3a2c-45e3-9c7c-26c578bde960.png)
