### ISSUE TITLE
页面demo点击一会页面卡死

### ISSUE THREAD

**Issue by feiyang0117** [JDFED/drip-table#346]
https://drip-table.jd.com/drip-table/demo，在线demo点击斑马线等等按钮来回切换几次页面卡死
![image](https://user-images.githubusercontent.com/10703466/210734695-85f6b04c-5206-4953-aeb4-758eddd3d32f.png)

**Comment by feiyang0117** [comment]
本地代码下载后点击一样的问题

**Comment by helloqian12138** [comment]
因为前段时间升级dumi2，导致版本不兼容，所以页面出现卡顿。然后我们接连因为新冠倒下，没来得及修复，实在不好意思。现在我们会尽快修复。

**Comment by helloqian12138** [comment]
https://github.com/ant-design/ant-design/pull/40158

**Comment by helloqian12138** [comment]
https://drip-table.jd.com/demo
