### ISSUE TITLE
官网 Demo 表格中向右插入列，输入数字提交后报错

### ISSUE THREAD

**Issue by vivipure** [JDFED/drip-table#349]
**Describe the bug**
官网 Demo 表格中向右插入列，输入数字提交后报错

**To Reproduce**
1. 选择一个表头
2. 点击菜单，点击 向右插入页
3. 输入数字，提交
4. 看到报错

**Expected behavior**
正常插入列

**Screenshots**
![image](https://user-images.githubusercontent.com/26271337/217470478-8d811a5c-7c2e-4578-8184-8e0e96d3f090.png)

**Comment by helloqian12138** [comment]
感谢反馈，我们这边看一下

**Comment by helloqian12138** [comment]
![image](https://user-images.githubusercontent.com/13211910/219609681-ab6729c2-c3ca-49ea-8026-1b624f665b39.png)
