### ISSUE TITLE
添加本地的筛选和筛选相关的api

### ISSUE THREAD

**Issue by pk111and222** [JDFED/drip-table#51]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
能够有api是关于本地筛选字段或者远程筛选字段的相关内容

**Describe alternatives you've considered**

**Additional context**
添加本地的筛选和筛选相关的api

**Comment by tinymins** [comment]
@pk111and222 请问指的是，表格 `列` 表头支持筛选数据功能吗？（类似 Excel 表头）
![image](https://user-images.githubusercontent.com/1808990/147652868-b74ff16c-35c3-4791-90fa-9bca0a5cab3c.png)

**Comment by tinymins** [comment]
Supported

**Comment by raoenhui** [comment]
api链接为[http://drip-table.jd.com/drip-table/functions](http://drip-table.jd.com/drip-table/functions),案例可以看[demo](http://drip-table.jd.com/drip-table/sample)
