### ISSUE TITLE
是否支持大数据量渲染和勾选

### ISSUE THREAD

**Issue by strongyc** [JDFED/drip-table#69]
是否支持大数据量渲染以及勾选，比如Surely Vue。

**Comment by raoenhui** [comment]
Drip-table可以支持大数据量渲染，打开虚拟列表配置即可。详情可看[http://drip-table.jd.com/drip-table/functions](http://drip-table.jd.com/drip-table/functions)。可视化搭建界面虚拟列表配置还在开发中，尽情期待^ _ ^
![image](https://user-images.githubusercontent.com/14011130/149124542-5187b288-0969-4bab-8c9d-d094e7df6eba.png)

**Comment by tinymins** [comment]
是支持大数据虚拟滚动的，可参见文档 https://drip-table.jd.com/drip-table/schema/virtual 。
