### ISSUE TITLE
自定义组件代码编辑器一直loading无法展示

### ISSUE THREAD

**Issue by untitled-coder** [JDFED/drip-table#74]
**Describe the bug**
选择自定义组件后，编辑自定义组件代码无法展示编辑器，一直在loading状态

**To Reproduce**
1. Go to 'http://drip-table.jd.com/demo'
2. 断开网络
3. Click on '自定义组件'，check '自定义组件' table cell
4. 属性配置 Scroll down to '代码编辑'
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tinymins** [comment]
Fixed, #75 .
