### ISSUE TITLE
antd V5 引入报错

### ISSUE THREAD

**Issue by strongyc** [JDFED/drip-table#82]
antd V5 引入报错？
devScripts.js:6523 [@umijs/runtime] load component failed Error: Module "./drip-table" does not exist in container.
while loading "./drip-table" from webpack/container/reference/mf
    at mf-va_remoteEntry.js:720

**Comment by helloqian12138** [comment]
你好，麻烦提供一下更精确的信息。目前我了解到的antd版本只到4.18.6呢。
Hello, please offer more infomation about your bug. The latest version of antd is 4.18.6 as far as I know.

**Comment by strongyc** [comment]
antd Pro V5

**Comment by helloqian12138** [comment]
原因：umijs会在src目录下创建.umi缓存目录，里面有一些配置；
解决方案：删除src/.umi目录，然后重启即可。
