### ISSUE TITLE
前端业务组件，第三方开发者在不发版情况下，怎么把自己业务组件导入Drip-table生成器中，方便产品拖拽

### ISSUE THREAD

**Issue by raoenhui** [JDFED/drip-table#85]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
增强自定义组件功能，新增可以输入链接地址的输入框，使第三方开发者的业务组件js链接贴入该输入框即可导入到Drip-Table中

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by helloqian12138** [comment]
已实现，文档：https://drip-table.jd.com/drip-table-generator/components/cdn-link
