### ISSUE TITLE
两个小问题，关于更多的table props 和虚拟列表rowSelection

### ISSUE THREAD

**Issue by a8b7** [JDFED/drip-table#96]
1. 能否支持 横向滚动和更多的table props
2. 虚拟列表选择 rowSelection 无效果

**Comment by raoenhui** [comment]
感谢您的问题
1、能否支持 横向滚动，我们本周支持。
2、更多的table props，这块可以再说具体点吗？
3、虚拟列表选择 rowSelection 无效果，我们本周修复。

**Comment by helloqian12138** [comment]
1. 横向滚动已支持，文档链接: https://drip-table.jd.com/drip-table/schema/scroll
2. table props 可以从官方文档查询: https://drip-table.jd.com/drip-table/props
3. rowSelection 目前涉及改动比较多，而且优先级不高，后续再计划实现。

**Comment by tinymins** [comment]
更新至 drip-table@2.x ，虚拟列表 rowSelect 已支持 https://drip-table.jd.com/drip-table/schema/virtual
